apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-data-backend-pvc
  namespace: prowlarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
