apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-data-backend-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: prowlarr-data-backend-pv
